### PR TITLE
fixing more math fonts

### PR DESCRIPTION
**Pull request by sshimizu2006**

### CODE REVIEW

**Comment by ikeuchi-screen** [comment]
@sshimizu2006 
Can you delete the file named **.DS_Store**?
I don't know why, I can't delete it.

**Comment by sshimizu2006** [comment]
I think I removed the file. Can you take a look at it?

**Comment by ikeuchi-screen** [comment]
Location **.DS_Store** changed from docs to root. It appears it still remains.

**Comment by sshimizu2006** [comment]
Oh, I removed the file.

**Pull request merged**
